### ISSUE TITLE
Implement Multi-Theme Support (White, Dark, OLED)

### ISSUE THREAD

**Issue by MathisVerstrepen** [MathisVerstrepen/Meridian#38]
This feature introduces the ability for users to customize the application's visual appearance by selecting from a predefined set of themes. This enhances user experience by providing personalization options and catering to different visual preferences.

### 1. Current State & Base Colors

The application currently uses a set of base CSS custom properties (variables) for its color palette, defined in `tailwind.config.js`:

```css
--color-soft-silk: #fffcf2;   /* Lightest background / primary text on dark */
--color-stone-gray: #ccc5b9;   /* Secondary light / borders */
--color-anthracite: #403d39;   /* Darker text / elements on light */
--color-obsidian: #252422;     /* Darkest background */
--color-ember-glow: #eb5e28;   /* Accent / Call-to-Action */
```

### 2. New Themes to Implement

We will implement three new themes, each overriding the base color variables to achieve a distinct look:

*   **White Theme:** A bright, high-contrast light theme.
*   **Dark Theme (ChatGPT-inspired):** A modern, subdued dark theme, similar to ChatGPT's default dark mode.
*   **OLED Theme:** A true black background theme, optimized for OLED displays to save power and provide deep contrast.

Here are the specific color overrides for each new theme:

```css
/* White Theme */
.theme-white {
    --color-soft-silk: #212121;  /* Primary text / darker elements */
    --color-stone-gray: #757575;  /* Secondary text / medium gray */
    --color-anthracite: #f5f5f5;  /* Secondary background / lighter elements */
    --color-obsidian: #ffffff;    /* Main background */
    --color-ember-glow: #eb5e28;  /* Accent color */
}

/* Dark Theme (ChatGPT-inspired) */
.theme-dark {
    --color-soft-silk: #d1d5db;  /* Light text */
    --color-stone-gray: #8e8ea0;  /* Medium gray for secondary text/borders */
    --color-anthracite: #444654;  /* Lighter dark background / card elements */
    --color-obsidian: #343541;    /* Main dark background */
    --color-ember-glow: #10a37f;  /* Accent changed to green/teal */
}

/* OLED Theme */
.theme-oled {
    --color-soft-silk: #e5e5e5;  /* Light text */
    --color-stone-gray: #a9a9a9;  /* Medium gray for secondary text/borders */
    --color-anthracite: #1a1a1a;  /* Very dark gray for elements */
    --color-obsidian: #000000;    /* True black background */
    --color-ember-glow: #10a37f;  /* Accent changed to green/teal */
}
```

![Image](https://github.com/user-attachments/assets/bec04459-77dd-4b5d-a5d1-e7c3d23744b7)

### 3. Implementation Details

*   **CSS Variable Overrides:**
    *   The new theme color definitions should be added as CSS classes (e.g., `.theme-white`, `.theme-dark`, `.theme-oled`) that apply to the `<html>` or `<body>` element of the application.
    *   These classes will override the default `--color-*` variables defined in `tailwind.config.js` when applied to the root element.

*   **Theme Application Mechanism:**
    *   The selected theme class (e.g., `theme-dark`) will be dynamically applied to the root `<html>` or `<body>` element of the application.
    *   Upon application load, the system will read the user's stored theme preference and apply the corresponding class.

*   **User Interface for Theme Selection:**
    *   **Location:** A new option or section will be added to the user's "Settings" page (e.g., under "Appearance" or "Display").
    *   **Control:** Radio buttons for each theme with small color swatches or previews next to each theme name to give a visual hint.
    *   **Instant Feedback:** When a user selects a new theme in the settings, the application's theme should change immediately to provide reactive feedback.

*   **Theme Persistence:**
    *   The user's selected theme preference (e.g., `"default"`, `"white"`, `"dark"`, `"oled"`) must be stored in the **user's profile in the database**.
    *   This ensures that the chosen theme persists across browser sessions and devices for the logged-in user.

*   **Default Theme:**
    *   If a user has not explicitly selected a theme, or for new users, the application should default to the current (base) theme. This can be represented by not applying any `.theme-*` class, allowing the base variables to take effect.

### 5. Considerations & Potential Challenges

*   **Hardcoded Colors:** Conduct a thorough audit of the existing codebase to identify and replace any hardcoded color values with the appropriate CSS variables. This is crucial for successful theming.
*   **SVG Icons:** Ensure that SVG icons either inherit colors via `currentColor` or can be dynamically styled to match the active theme's palette.
